name: Recovery CI

on:
  workflow_dispatch:

jobs:
  teamwin:
    name: TeamWin Recovery Builder
    runs-on: ubuntu-20.04

    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses5 axel python
          sudo ln -f -s /usr/bin/python2.7 /usr/bin/python
          
      - name: Install OpenJDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Sync TeamWin Recovery sources
        run: |
          mkdir ~/teamwin
          cd ~/teamwin
          mkdir ~/.bin
          sudo curl http://commondatastorage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/bin/repo > /dev/zero
          sudo chmod 777 /usr/bin/repo
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-7.1
          repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all) 2>&1
          git clone --depth=1 --branch twrp-7.1 --single-branch https://github.com/J110H-Android/twrp_device_samsung_j1pop3g.git device/samsung/j1pop3g

      - name: Build TeamWin Recovery
        run: |
          cd ~/teamwin
          source build/envsetup.sh
          export LC_ALL=C
          lunch omni_j1pop3g-eng
          make -j$(nproc --all) recoveryimage

      - name: Upload TeamWin Recovery builds
        uses: actions/upload-artifact@v2
        with:
          name: TeamWin_j1pop3g
          path: /home/runner/teamwin/out/target/product/j1pop3g/recovery.img

  orangefox:
    name: OrangeFox Recovery Builder
    runs-on: ubuntu-20.04

    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses5 axel python
          sudo ln -f -s /usr/bin/python2.7 /usr/bin/python
          
      - name: Install OpenJDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Sync OrangeFox Recovery sources
        run: |
          mkdir ~/orangefox
          cd ~/orangefox
          mkdir ~/.bin
          sudo curl http://commondatastorage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/bin/repo > /dev/zero
          sudo chmod 777 /usr/bin/repo
          repo init --depth=1 -u https://github.com/unlegacy-devices/fox-7.1_manifest.git -b twrp-7.1
          repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all) 2>&1
          git clone --depth=1 --branch twrp-7.1 --single-branch https://github.com/J110H-Android/twrp_device_samsung_j1pop3g.git device/samsung/j1pop3g

      - name: Build OrangeFox Recovery
        run: |
          cd ~/orangefox
          source build/envsetup.sh
          curl https://avatars.githubusercontent.com/u/99538268 --output - > /home/runner/maintainer.png
          convert /home/runner/maintainer.png -resize 192x192 /home/runner/maintainer.png
          export OF_MAINTAINER="J110H-Android"
          export OF_MAINTAINER_AVATAR="/home/runner/maintainer.png"
          export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
          export OF_LEGACY_SHAR512=1
          export OF_DISABLE_MIUI_SPECIFIC_FEATURES=1
          export LC_ALL=C
          lunch omni_j1pop3g-eng
          make -j$(nproc --all) recoveryimage

      - name: Upload OrangeFox Recovery builds
        uses: actions/upload-artifact@v2
        with:
          name: OrangeFox_j1pop3g
          path: |
            /home/runner/orangefox/out/target/product/j1pop3g/recovery.img
            /home/runner/orangefox/out/target/product/j1pop3g/OrangeFox-*.zip

  skyhawk:
    name: SkyHawk Recovery Builder
    runs-on: ubuntu-20.04

    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses5 axel python
          sudo ln -f -s /usr/bin/python2.7 /usr/bin/python
          
      - name: Install OpenJDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Sync SkyHawk Recovery sources
        run: |
          mkdir ~/skyhawk
          cd ~/skyhawk
          mkdir ~/.bin
          sudo curl http://commondatastorage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/bin/repo > /dev/zero
          sudo chmod 777 /usr/bin/repo
          repo init --depth=1 -u https://github.com/unlegacy-devices/manifest -b v3_9.0
          repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all) 2>&1
          git clone --depth=1 --branch twrp-7.1 --single-branch https://github.com/J110H-Android/twrp_device_samsung_j1pop3g.git device/samsung/j1pop3g

      - name: Build SkyHawk Recovery
        run: |
          cd ~/skyhawk
          source build/envsetup.sh
          export LC_ALL=C
          lunch omni_j1pop3g-eng
          make -j$(nproc --all) recoveryimage

      - name: Upload SkyHawk Recovery builds
        uses: actions/upload-artifact@v2
        with:
          name: SkyHawk_j1pop3g
          path: |
            /home/runner/skyhawk/out/target/product/j1pop3g/recovery.img
            /home/runner/skyhawk/out/target/product/j1pop3g/*.zip
