name: Recovery CI

on:
  workflow_dispatch:

jobs:
  teamwin:
    name: TeamWin Recovery Builder
    runs-on: ubuntu-18.04

    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install zip gcc-multilib g++-multilib \
            libc6-dev-i386 lib32ncurses5-dev lib32z1-dev \
            libgl1-mesa-dev libxml2-utils xsltproc schedtool
          sudo ln -f -s /usr/bin/python2.7 /usr/bin/python

      - name: Sync TeamWin Recovery sources
        run: |
          mkdir ~/teamwin
          cd ~/teamwin

          mkdir ~/.bin
          sudo curl http://commondatastorage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/bin/repo > /dev/zero
          sudo chmod 777 /usr/bin/repo
          repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_lineageos.git -b twrp-14.1
          repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all) 2>&1
          git clone --depth=1 --branch cm-14.1 --single-branch https://github.com/J110H-Android/twrp_device_samsung_j1pop3g.git device/samsung/j1pop3g

      - name: Build TeamWin Recovery
        run: |
          cd ~/teamwin
          source build/envsetup.sh
          export LC_ALL=C
          export RECOVERY_VARIANT=twrp
          lunch omni_j1pop3g-eng
          make -j$(nproc --all) recoveryimage

      - name: Upload TeamWin Recovery builds
        uses: actions/upload-artifact@v2
        with:
          name: TeamWin_j1pop3g
          path: /home/runner/teamwin/out/target/product/j1pop3g/recovery.img

  lineage:
    name: LineageOS Recovery Builder
    runs-on: ubuntu-18.04

    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install zip gcc-multilib g++-multilib \
            libc6-dev-i386 lib32ncurses5-dev lib32z1-dev \
            libgl1-mesa-dev libxml2-utils xsltproc schedtool
          sudo ln -f -s /usr/bin/python2.7 /usr/bin/python

      - name: Sync LineageOS Recovery sources
        run: |
          mkdir ~/lineage
          cd ~/lineage
          mkdir ~/.bin
          sudo curl http://commondatastorage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/bin/repo > /dev/zero
          sudo chmod 777 /usr/bin/repo
          repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_lineageos.git -b twrp-14.1
          repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all) 2>&1
          git clone --depth=1 --branch cm-14.1 --single-branch https://github.com/J110H-Android/twrp_device_samsung_j1pop3g.git device/samsung/j1pop3g

      - name: Build LineageOS Recovery
        run: |
          cd ~/lineage
          source build/envsetup.sh
          export LC_ALL=C
          lunch omni_j1pop3g-eng
          make -j$(nproc --all) recoveryimage

      - name: Upload LineageOS Recovery builds
        uses: actions/upload-artifact@v2
        with:
          name: LineageOS-Recovery_j1pop3g
          path: |
            /home/runner/lineage/out/target/product/j1pop3g/recovery.img
